import * as XLSX from 'xlsx';

export type MarketValueRecord = { property: string; marketValue: number; asOf: string; valueType: string; source: string };
export class MarketValueImportError extends Error { override name = 'MarketValueImportError'; }
const key = (value: unknown) => String(value ?? '').trim().toLowerCase().replace(/[^a-z0-9]/g, ''); const text = (row: unknown[], index: number) => String(row[index] ?? '').trim(); const amount = (value: unknown) => Math.max(0, Number(String(value ?? '').replace(/[^0-9.-]/g, '')) || 0); const columnFor = (headers: string[], names: string[]) => headers.findIndex((header) => names.includes(header));
/** Reads valuation, appraisal, listing, or property-financial reports with a property/value column. */
export function parseMarketValueWorkbook(data: ArrayBuffer): MarketValueRecord[] { const workbook = XLSX.read(new Uint8Array(data), { type: 'array' }); const sheetName = workbook.SheetNames[0]; const sheet = sheetName ? workbook.Sheets[sheetName] : undefined; const rows = sheet ? XLSX.utils.sheet_to_json<unknown[]>(sheet, { header: 1, defval: '' }) : []; const headerRow = rows.findIndex((row) => row.map(key).some((header) => ['property', 'propertyname', 'address', 'building', 'asset'].includes(header))); if (headerRow < 0) throw new MarketValueImportError('Could not find a Property or Address column in the Market Value report.'); const headers = rows[headerRow]!.map(key); const property = columnFor(headers, ['property', 'propertyname', 'address', 'building', 'asset']); const value = columnFor(headers, ['marketvalue', 'value', 'appraisedvalue', 'valuation', 'fairmarketvalue']); const asOf = columnFor(headers, ['asof', 'asofdate', 'valuationdate', 'appraisaldate', 'reportdate', 'date']); const valueType = columnFor(headers, ['valuetype', 'type', 'basis']); if (value < 0) throw new MarketValueImportError('The Market Value report needs a Market Value, Value, or Appraised Value column.'); const records = rows.slice(headerRow + 1).map((row, rowIndex) => ({ property: text(row, property), marketValue: amount(row[value]), asOf: asOf >= 0 ? text(row, asOf) : '', valueType: valueType >= 0 ? text(row, valueType) : '', source: `${sheetName ?? 'Report'} row ${headerRow + rowIndex + 2}` })).filter((record) => record.property); if (!records.length) throw new MarketValueImportError('No property rows were found in the Market Value report.'); return records; }
export function buildMarketValueTemplateWorkbook(): XLSX.WorkBook { const workbook = XLSX.utils.book_new(); const sheet = XLSX.utils.aoa_to_sheet([['Market Value Import'], ['Property', 'Market Value', 'As Of', 'Value Type'], ...Array.from({ length: 20 }, () => ['', '', '', ''])]); sheet['!cols'] = [32, 18, 16, 22].map((wch) => ({ wch })); XLSX.utils.book_append_sheet(workbook, sheet, 'Market Value'); return workbook; }
export function downloadMarketValueTemplate() { XLSX.writeFile(buildMarketValueTemplateWorkbook(), 'Market Value Fallback Template.xlsx'); }
export function downloadMarketValueWorkbook(records: readonly MarketValueRecord[]) { const workbook = XLSX.utils.book_new(); const sheet = XLSX.utils.aoa_to_sheet([['Market Value Export'], ['Property', 'Market Value', 'As Of', 'Value Type', 'Source'], ...records.map((r) => [r.property, r.marketValue, r.asOf, r.valueType, r.source])]); sheet['!cols'] = [32, 18, 16, 22, 22].map((wch) => ({ wch })); XLSX.utils.book_append_sheet(workbook, sheet, 'Market Value'); XLSX.writeFile(workbook, 'Market Value Export.xlsx'); }
