import * as XLSX from 'xlsx';
import { propertyMatches } from './property-match';

export type MarketValueSource = 'bov' | 'appraisal' | 'income-model' | 'city-appraised' | 'construction-land' | 'comps' | 'legacy';
export type MarketValueTemplateSource = Extract<MarketValueSource, 'bov' | 'city-appraised' | 'comps'>;
export type MarketValueRecord = { property: string; marketValue: number; asOf: string; valueType: string; source: string; id?: string; provider?: string; sourceKind?: MarketValueSource; selected?: boolean; capRate?: number };
export class MarketValueImportError extends Error { override name = 'MarketValueImportError'; }
const key = (value: unknown) => String(value ?? '').trim().toLowerCase().replace(/[^a-z0-9]/g, ''); const text = (row: unknown[], index: number) => String(row[index] ?? '').trim(); const amount = (value: unknown) => Math.max(0, Number(String(value ?? '').replace(/[^0-9.-]/g, '')) || 0); const columnFor = (headers: string[], names: string[]) => headers.findIndex((header) => names.includes(header));
/** Reads valuation, appraisal, listing, or property-financial reports with a property/value column. */
export function parseMarketValueWorkbook(data: ArrayBuffer): MarketValueRecord[] { const workbook = XLSX.read(new Uint8Array(data), { type: 'array' }); const sheetName = workbook.SheetNames[0]; const sheet = sheetName ? workbook.Sheets[sheetName] : undefined; const rows = sheet ? XLSX.utils.sheet_to_json<unknown[]>(sheet, { header: 1, defval: '' }) : []; const headerRow = rows.findIndex((row) => row.map(key).some((header) => ['property', 'propertyname', 'address', 'building', 'asset'].includes(header))); if (headerRow < 0) throw new MarketValueImportError('Could not find a Property or Address column in the Market Value report.'); const headers = rows[headerRow]!.map(key); const property = columnFor(headers, ['property', 'propertyname', 'address', 'building', 'asset']); const value = columnFor(headers, ['marketvalue', 'value', 'appraisedvalue', 'valuation', 'fairmarketvalue']); const asOf = columnFor(headers, ['asof', 'asofdate', 'valuationdate', 'appraisaldate', 'reportdate', 'date']); const valueType = columnFor(headers, ['valuetype', 'type', 'basis']); if (value < 0) throw new MarketValueImportError('The Market Value report needs a Market Value, Value, or Appraised Value column.'); const records = rows.slice(headerRow + 1).map((row, rowIndex) => ({ property: text(row, property), marketValue: amount(row[value]), asOf: asOf >= 0 ? text(row, asOf) : '', valueType: valueType >= 0 ? text(row, valueType) : '', source: `${sheetName ?? 'Report'} row ${headerRow + rowIndex + 2}` })).filter((record) => record.property); if (!records.length) throw new MarketValueImportError('No property rows were found in the Market Value report.'); return records; }
const templateDetails: Record<MarketValueTemplateSource, { title: string; filename: string }> = { bov: { title: 'Broker’s Opinion of Value Manual Import', filename: 'Broker Opinion of Value Manual Template.xlsx' }, 'city-appraised': { title: 'City Assessed Value Manual Import', filename: 'City Assessed Value Manual Template.xlsx' }, comps: { title: 'Comparable Sales Manual Import', filename: 'Comparable Sales Manual Template.xlsx' } };
export function buildMarketValueTemplateWorkbook(kind: MarketValueTemplateSource = 'bov'): XLSX.WorkBook { const template = templateDetails[kind]; const workbook = XLSX.utils.book_new(); const sheet = XLSX.utils.aoa_to_sheet([[template.title], ['Property', 'Market Value', 'As Of', 'Value Type'], ...Array.from({ length: 20 }, () => ['', '', '', ''])]); sheet['!cols'] = [32, 18, 16, 22].map((wch) => ({ wch })); XLSX.utils.book_append_sheet(workbook, sheet, 'Market Value'); return workbook; }
export function downloadMarketValueTemplate(kind: MarketValueTemplateSource = 'bov') { XLSX.writeFile(buildMarketValueTemplateWorkbook(kind), templateDetails[kind].filename); }
const exportColumns: Array<[MarketValueSource, string]> = [['bov', 'Broker’s Opinion of Value'], ['city-appraised', 'City Assessed Value'], ['comps', 'Comparable Sales'], ['appraisal', 'Appraisal'], ['income-model', 'Income Model'], ['construction-land', 'Construction / Land Value Model'], ['legacy', 'Other / Legacy Value']];
export function buildMarketValueExportWorkbook(records: readonly MarketValueRecord[], properties: readonly string[] = []): XLSX.WorkBook {
  const propertyNames = [...properties, ...records.map((record) => record.property)].reduce<string[]>((unique, property) => unique.some((existing) => propertyMatches(existing, property)) ? unique : [...unique, property], []).sort((left, right) => left.localeCompare(right, undefined, { numeric: true, sensitivity: 'base' }));
  const recordFor = (property: string, kind: MarketValueSource) => records.find((record) => propertyMatches(record.property, property) && (record.sourceKind ?? 'legacy') === kind);
  const selectedFor = (property: string) => records.find((record) => propertyMatches(record.property, property) && record.selected) ?? records.find((record) => propertyMatches(record.property, property));
  const sheet = XLSX.utils.aoa_to_sheet([['Market Value Export'], ['Property', 'Selected Valuation', 'Selected Market Value', ...exportColumns.map(([, label]) => label)], ...propertyNames.map((property) => { const selected = selectedFor(property); return [property, selected?.valueType ?? '', selected?.marketValue ?? '', ...exportColumns.map(([kind]) => recordFor(property, kind)?.marketValue ?? '')]; })]);
  sheet['!cols'] = [32, 28, 22, ...exportColumns.map(() => 26)].map((wch) => ({ wch }));
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, sheet, 'Market Value');
  return workbook;
}
export function downloadMarketValueWorkbook(records: readonly MarketValueRecord[], properties: readonly string[] = []) { XLSX.writeFile(buildMarketValueExportWorkbook(records, properties), 'Market Value Export.xlsx'); }
